elasticsearch:
    cluster:
        name: haxiha-es
    ip: 172.16.1.237,172.16.1.238,172.16.1.239
    pool: 10
    port: 8301
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
feign:
    httpclient:
        enabled: true
oss:
    access:
        #阿里云API的密钥Access Key ID
        key: LTAI
        #阿里云API的密钥Access Key Secret
        secret: ARE
    #阿里云API的bucket名称
    bucket:
        name: dev-saas-haxiha
    #阿里云API的内或外网域名
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
haxiha:
    #不需要检查的APPID
    appid:
        nocheck: 1
    #不要拦截的地址
    url:
        nocheck: /setting/menu/updateJson,/member/user/newPwd,/member/invitecode/checkValid,/wechat/event,/sales/marketing/keyword,goods/category/recommend,/setting/area/json,/marketing/advertslist/position,/setting/saas/info,/sales/marketing/activity,/marketing/goodsposition/position,/setting/area/defualt,/member/user/forget_pwd,/search,/home,/marketing/articlelist,/user/login,/user/wxlogin,/msgcode,/captcha,/register,/callback/notify,/callback/return,/callback/notify/refund,base/alldic,/onPay,order/api/paysuccess,/allinpay/callback/pickupUrl,sales/coupon/canGrant,/bench/fx,/marketing/goodsgroup/actlist,/marketing/goodsgroup/actGoodsList,/marketing/goodsgroup/listAll,/goods/data/migrate,/admin/user/login,/admin/user/captcha
    #本地上传local与阿里云oss上传标记
    upload:
        mode: oss
    #物理路径
    storage:
        path: /data/haxiha/img
    #访问路径
    access:
        path: http://img.dev.haxiha.com
    #member模块
    staff:
        mobile: 17792754650
#日志级别
logging:
    level:
        com:
            haxiha: DEBUG
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
    typeAliasesPackage: com.haxiha.**.domain
    mapperLocations: classpath*:com/haxiha/**/*.xml

public-key: MFwwDQYJKoZI
spring:
    application:
        env: pre
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    cloud:
        bus:
            enabled: true
        stream:
            bindings: 
                goods:
                    destination: haxiha-goods
                    group: goods
                    consumer:
                        concurrency: 1
                        partitioned: false
                order:
                    destination: haxiha-order
                    group: order
                    consumer:
                        concurrency: 1
                        partitioned: false
            kafka:
                 binder:
                    brokers: 172.16.1.237:9191,172.16.1.238:9191,172.16.1.239:9191
                    zk-nodes: 172.16.1.237:1181,172.16.1.238:1181,172.16.1.239:1181
                    minPartitionCount: 1
                    autoCreateTopics: true
                    autoAddPartitions: true   
    http:
        multipart:
            maxFileSize: 15MB
            maxRequestSize: 15MB
    #邮箱日志提醒  未开启
    mail:
        host: smtp.ym.163.com
        port: 25
        username: no@haxiha.com
        password: 9
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    boot:
        admin:
            notify:
                #EmailConfig类
                mail:
                    from: no@haxiha.com
                    to: luo@haxiha.com
                    enabled: false
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        filters: 'stat,wall,log4j  '
        initialSize: 5.0
        maxActive: 20.0
        maxPoolPreparedStatementPerConnectionSize: 20.0
        maxWait: 60000.0
        minEvictableIdleTimeMillis: 300000.0
        minIdle: 5.0
        password: Jkdz8888
        poolPreparedStatements: 'true  '
        testOnBorrow: 'false  '
        testOnReturn: 'false  '
        testWhileIdle: 'true  '
        timeBetweenEvictionRunsMillis: 60000.0
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://172.16.1.237:3306/spring?useUnicode=true&characterEncoding=UTF-8
        username: admin
        validationQuery: 'SELECT 1 FROM DUAL  '

    redis:
        database: 0
        cluster:
            nodes: 172.16.1.237:6381,172.16.1.237:6382,172.16.1.238:6383,172.16.1.238:6384,172.16.1.239:6385,172.16.1.239:6386
        password:
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
        timeout: 0


    kafka:
        bootstrap-servers: 172.16.1.237:9191,172.16.1.238:9191,172.16.1.239:9191
        custom-producer:
            acks: all
            retries: 10
            batch-size: 16384
            linger-ms: 1
            buffer-memory: 33554432
            request-timeout-ms: 10000
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        custom-consumer:
            group-id: testTopic
            enable-auto-commit: false
            auto-commit-interval: 1000
            auto-offset-reset: earliest
            max-poll-records: 100
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    sleuth:
        #监控开关
        enabled: true
        #采样率
        sampler:
            percentage: 1
    zipkin:
        base-url: http://${spring.cloud.client.ipAddress}:7046
        #本项目服务名
        service:
           name: ${spring.application.name}
swagger:
    base-package: com.haxiha
    base-path: /**
    contact:
        email: 292224657@qq.com
        name: junkai
        url: http://www.jkslw.com
    description: Starter for swagger 2.x
    exclude-path: /error, /ops/**
    license: Apache License, Version 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
    title: spring-boot-starter-swagger
    version: 1.1.0.RELEASE
info:
    group: 君凯技术中心
    description: 有想法就要行动，哪怕失败告终，拖拉会让你丧失机会。想法只有化作行动，才有达成愿望的可能，否则想法永远是想法。没有想法的人，不会成功，但只有想法没有行动的人，也不会有任何成就!
    members: all boys
    tell: 400-900-2165
    module: haxiha-gateway-service
